bil_1 = int(input("Input Bilangan Pertama : "))
bil_2 = int(input("Input Bilangan Kedua : "))
print(f"Hasil Penjumlahan {bil_1} dan {bil_2} adalah {bil_1+bil_2}")
print(f"Hasil Pengurangan {bil_1} dan {bil_2} adalah {bil_1-bil_2}")
print(f"Hasil Modulus {bil_1} dan {bil_2} adalah {bil_1%bil_2}")